import type {
  ExerciseMuscleGroup,
  MovementType,
  MuscleType,
  WarmupType,
  WeightType,
} from "./types.js";

export type ExerciseData = {
  id: string;
  name: string;
  weightType: WeightType;
  muscleType: MuscleType;
  muscleGroups: readonly ExerciseMuscleGroup[];
  movementType: MovementType;
  warmupType: WarmupType;
  warmupEnabledByDefault: boolean;
  usesBarbellWeightInWarmup: boolean;
  defaultBarbellWeightKg: number;
  defaultBarbellWeightLb: number;
  shortVideoUrl: string;
  fullVideoUrl: string;
};

export const exercises: ExerciseData[] = [
  {
    id: "SL_AbWheel",
    name: "Ab Wheel",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_AbWheel.mp4",
    fullVideoUrl: "https://youtu.be/RSz1-ZQCCtU",
    movementType: "MISC",
    muscleType: "ABS",
    muscleGroups: [
      { muscle: "abs", stress: "HIGH" },
      { muscle: "obliques", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_BandPullApart",
    name: "Band Pull-apart",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_BandPullApart.mp4",
    fullVideoUrl: "https://youtu.be/rotnvcAP23E",
    movementType: "HORIZONTAL_PULL",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "rear_delts", stress: "HIGH" },
      { muscle: "traps", stress: "HIGH" },
      { muscle: "upper_traps", stress: "LOW" },
    ],
    weightType: "OTHER",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_BarbellCurls",
    name: "Barbell Curls",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_BarbellCurls.mp4",
    fullVideoUrl: "https://youtu.be/QelR1IuSU6o",
    movementType: "MISC",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "biceps", stress: "HIGH" },
      { muscle: "forearms", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_ISO",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_BarbellRow",
    name: "Barbell Row",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_BarbellRow.mp4",
    fullVideoUrl: "https://youtu.be/-KSuEJ62Bx0",
    movementType: "HORIZONTAL_PULL",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lats", stress: "HIGH" },
      { muscle: "traps", stress: "LOW" },
      { muscle: "biceps", stress: "LOW" },
      { muscle: "rear_delts", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_BarbellShrug",
    name: "Barbell Shrug",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_BarbellShrug.mp4",
    fullVideoUrl: "https://youtu.be/4O130Isdan8",
    movementType: "VERTICAL_PUSH",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "upper_traps", stress: "HIGH" },
      { muscle: "forearms", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_BehindNeckPress",
    name: "Behind The Neck Press",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_BehindNeckPress.mp4",
    fullVideoUrl: "https://youtu.be/z2OD4yUjNik",
    movementType: "VERTICAL_PUSH",
    muscleType: "SHOULDERS",
    muscleGroups: [
      { muscle: "shoulders", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "upper_traps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_BenchCamberedBar",
    name: "Bench Cambered Bar",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_BenchCamberedBar.mp4",
    fullVideoUrl: "https://youtu.be/x1U-Tuu25ks",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_BenchDips",
    name: "Bench Dips",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_BenchDips.mp4",
    fullVideoUrl: "https://youtu.be/mnTeplOcvtQ",
    movementType: "VERTICAL_PUSH",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "triceps", stress: "HIGH" },
      { muscle: "pects", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "NONE",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_BenchFeetUp",
    name: "Bench Feet Up",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_BenchFeetUp.mp4",
    fullVideoUrl: "https://youtu.be/oGFGqaHpa6A",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_BenchPress",
    name: "Bench Press",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_BenchPress.mp4",
    fullVideoUrl: "https://youtu.be/IK-IgTOKc6o",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_BenchPressTempo310",
    name: "Bench Press 310 Tempo",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_BenchPressTempo310.mp4",
    fullVideoUrl: "https://youtu.be/JyUt6Of-WLU",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_BenchTouchGo",
    name: "Bench Touch & Go",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_BenchTouchGo.mp4",
    fullVideoUrl: "https://youtu.be/4UiWOiu5aD0",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_BoardPress",
    name: "Board Press",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_BoardPress.mp4",
    fullVideoUrl: "https://youtu.be/o6cO6g4VfVo",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "triceps", stress: "HIGH" },
      { muscle: "pects", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_BoxSquat",
    name: "Box Squat",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_BoxSquat.mp4",
    fullVideoUrl: "https://youtu.be/-di3443imSE",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_BulgarianSplitSquat",
    name: "Bulgarian Split Squat",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_BulgarianSplitSquat.mp4",
    fullVideoUrl: "https://youtu.be/29z966abW0Y",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_CableCrunch",
    name: "Ab Pulldown",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_CableCrunch.mp4",
    fullVideoUrl: "https://youtu.be/4My-wh1tsYM",
    movementType: "MISC",
    muscleType: "ABS",
    muscleGroups: [
      { muscle: "abs", stress: "HIGH" },
      { muscle: "obliques", stress: "LOW" },
    ],
    weightType: "MACHINE",
    warmupType: "MACHINE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_Chinups",
    name: "Chinups",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_Chinups.mp4",
    fullVideoUrl: "https://youtu.be/RH11GAOKv-w",
    movementType: "VERTICAL_PULL",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "biceps", stress: "HIGH" },
      { muscle: "lats", stress: "LOW" },
      { muscle: "forearms", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_CloseGripBenchFeetUp",
    name: "Close Grip Bench Feet Up",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_CloseGripBenchFeetUp.mp4",
    fullVideoUrl: "https://youtu.be/uEPMZn2X9-Y",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_CloseGripBenchIncline",
    name: "Close Grip Bench Incline",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_CloseGripBenchIncline.mp4",
    fullVideoUrl: "https://youtu.be/Bvyw98ZEn2Y",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "shoulders", stress: "LOW" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_CloseGripBenchPress",
    name: "Close Grip Bench Press",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_CloseGripBenchPress.mp4",
    fullVideoUrl: "https://youtu.be/atyEjupHrO0",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "triceps", stress: "HIGH" },
      { muscle: "pects", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_CloseGripBoardPress",
    name: "Close Grip Board Press",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_CloseGripBoardPress.mp4",
    fullVideoUrl: "https://youtu.be/7qZKL_Ias44",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "triceps", stress: "HIGH" },
      { muscle: "pects", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_CloseGripFloorPress",
    name: "Close Grip Floor Press",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_CloseGripFloorPress.mp4",
    fullVideoUrl: "https://youtu.be/m-k_ondn-YM",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "triceps", stress: "HIGH" },
      { muscle: "pects", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_DBHipThrust",
    name: "Dumbbell Hip Thrust",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DBHipThrust.mp4",
    fullVideoUrl: "https://youtu.be/2axifP_Bii8",
    movementType: "HIP_HINGE",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "glutes", stress: "HIGH" },
      { muscle: "hamstrings", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_Deadlift",
    name: "Deadlift",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_Deadlift.mp4",
    fullVideoUrl: "https://youtu.be/uKmwAqs_lFw",
    movementType: "HIP_HINGE",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lower_back", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "upper_traps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_Deadlift600",
    name: "Tempo Deadlift 600",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_Deadlift600.mp4",
    fullVideoUrl: "https://youtu.be/doKsysBpze8",
    movementType: "HIP_HINGE",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lower_back", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "upper_traps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_DeficitDeadlift",
    name: "Deficit Deadlift",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DeficitDeadlift.mp4",
    fullVideoUrl: "https://youtu.be/-iINFC-Fxbc",
    movementType: "HIP_HINGE",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lower_back", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "upper_traps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_Dips",
    name: "Dips",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_Dips.mp4",
    fullVideoUrl: "https://youtu.be/B_tfB8mUzRg",
    movementType: "VERTICAL_PUSH",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "triceps", stress: "HIGH" },
      { muscle: "pects", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbbellPushPress",
    name: "Dumbbell Push Press",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbbellPushPress.mp4",
    fullVideoUrl: "https://youtu.be/lyoNzPqVO8Q",
    movementType: "VERTICAL_PUSH",
    muscleType: "SHOULDERS",
    muscleGroups: [
      { muscle: "shoulders", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellBench1Arm",
    name: "Dumbbell Bench 1 arm",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellBench1Arm.mp4",
    fullVideoUrl: "https://youtu.be/OwTUV8TTmQs",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellBenchFeetUp",
    name: "Dumbbell Bench Feet up",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellBenchFeetUp.mp4",
    fullVideoUrl: "https://youtu.be/lh8CKb_JTt8",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellBenchFloor",
    name: "Dumbbell Bench Floor",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellBenchFloor.mp4",
    fullVideoUrl: "https://youtu.be/ktNEs88chTA",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "triceps", stress: "HIGH" },
      { muscle: "pects", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellBenchPause",
    name: "Dumbbell Bench Pause",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellBenchPause.mp4",
    fullVideoUrl: "https://youtu.be/G0jY-5EIP18",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellBenchPress",
    name: "Dumbbell Bench Press",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellBenchPress.mp4",
    fullVideoUrl: "https://youtu.be/c_0rlUA2b8s",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellBulgarianSplitSquat",
    name: "Dumbbell Bulgarian Split Squat",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellBulgarianSplitSquat.mp4",
    fullVideoUrl: "https://youtu.be/cYuAdiSjTxA",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellCurl",
    name: "Dumbbell Curl",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellCurl.mp4",
    fullVideoUrl: "https://youtu.be/M3fKUn26zwE",
    movementType: "MISC",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "biceps", stress: "HIGH" },
      { muscle: "forearms", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellFly",
    name: "Dumbbell Fly",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellFly.mp4",
    fullVideoUrl: "https://youtu.be/LINU7cetbq8",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellFrrontSquat",
    name: "Dumbbell Front Squat",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellFrrontSquat.mp4",
    fullVideoUrl: "https://youtu.be/aSk2sHxr84k",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellLunch",
    name: "Dumbbell Lunge",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellLunch.mp4",
    fullVideoUrl: "https://youtu.be/EC5yYj57FxM",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellOHPress",
    name: "Dumbbell Overhead Press",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellOHPress.mp4",
    fullVideoUrl: "https://youtu.be/NEu5MefpW0g",
    movementType: "VERTICAL_PUSH",
    muscleType: "SHOULDERS",
    muscleGroups: [
      { muscle: "shoulders", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellOHPress1Arm",
    name: "Dumbbell Overhead Press 1 arm",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellOHPress1Arm.mp4",
    fullVideoUrl: "https://youtu.be/ADlUFj8OoYY",
    movementType: "VERTICAL_PUSH",
    muscleType: "SHOULDERS",
    muscleGroups: [
      { muscle: "shoulders", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellOverheadPressSeated",
    name: "Dumbbell Overhead Press Seated",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellOverheadPressSeated.mp4",
    fullVideoUrl: "https://youtu.be/rg4jg5xIGiM",
    movementType: "VERTICAL_PUSH",
    muscleType: "SHOULDERS",
    muscleGroups: [
      { muscle: "shoulders", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellPreacherCurl",
    name: "Dumbbell Preacher Curl",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellPreacherCurl.mp4",
    fullVideoUrl: "https://youtu.be/rWAScsWsugg",
    movementType: "MISC",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "biceps", stress: "HIGH" },
      { muscle: "forearms", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellPushPress1Arm",
    name: "Dumbbell Push Press 1 arm",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellPushPress1Arm.mp4",
    fullVideoUrl: "https://youtu.be/9yheoM9erDM",
    movementType: "VERTICAL_PUSH",
    muscleType: "SHOULDERS",
    muscleGroups: [
      { muscle: "shoulders", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellPullover",
    name: "Dumbbell Pullover",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellPullover.mp4",
    fullVideoUrl: "https://youtu.be/Gej-s1vfJ9g",
    movementType: "VERTICAL_PULL",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lats", stress: "HIGH" },
      { muscle: "pects", stress: "LOW" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellReverseLunge",
    name: "Dumbbell Reverse Lunge",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellReverseLunge.mp4",
    fullVideoUrl: "https://youtu.be/Jbi8nugooow",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellRomanianDeadlift",
    name: "Dumbbell Romanian Deadlift",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellRomanianDeadlift.mp4",
    fullVideoUrl: "https://youtu.be/chwEMwgMkqs",
    movementType: "HIP_HINGE",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "hamstrings", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "lower_back", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellRomanianDeadlift1Leg",
    name: "Dumbbell Romanian Deadlift 1 Leg",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellRomanianDeadlift1Leg.mp4",
    fullVideoUrl: "https://youtu.be/9pqtG0aj26Y",
    movementType: "HIP_HINGE",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "hamstrings", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "lower_back", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellRow",
    name: "Dumbbell Row",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellRow.mp4",
    fullVideoUrl: "https://youtu.be/WNqw-y6h2wc",
    movementType: "HORIZONTAL_PULL",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lats", stress: "HIGH" },
      { muscle: "traps", stress: "LOW" },
      { muscle: "biceps", stress: "LOW" },
      { muscle: "rear_delts", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellShrug",
    name: "Dumbbell Shrug",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellShrug.mp4",
    fullVideoUrl: "https://youtu.be/kkp-9x7o1a4",
    movementType: "VERTICAL_PUSH",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "upper_traps", stress: "HIGH" },
      { muscle: "forearms", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellSplitSquat",
    name: "Dumbbell Split Squat",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellSplitSquat.mp4",
    fullVideoUrl: "https://youtu.be/aGz7MLy6q3Y",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellStepUp",
    name: "Dumbbell Stepup",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellStepUp.mp4",
    fullVideoUrl: "https://youtu.be/yom1MRZArG8",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_DumbbellTricepsExtension",
    name: "Dumbbell Triceps Extension",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_DumbbellTricepsExtension.mp4",
    fullVideoUrl: "https://youtu.be/kJ0H5Zhb_uc",
    movementType: "MISC",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "triceps", stress: "HIGH" },
      { muscle: "forearms", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_EzBarCurl",
    name: "Ez-bar Curl",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_EzBarCurl.mp4",
    fullVideoUrl: "https://youtu.be/r8ZlBIHaJ90",
    movementType: "MISC",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "biceps", stress: "HIGH" },
      { muscle: "forearms", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_ISO",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_FacePull",
    name: "Face Pull",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_FacePull.mp4",
    fullVideoUrl: "https://youtu.be/R3Q5f-pe0eg",
    movementType: "HORIZONTAL_PULL",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "rear_delts", stress: "HIGH" },
      { muscle: "traps", stress: "LOW" },
      { muscle: "upper_traps", stress: "LOW" },
    ],
    weightType: "MACHINE",
    warmupType: "MACHINE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_FloorPress",
    name: "Floor Press",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_FloorPress.mp4",
    fullVideoUrl: "https://youtu.be/qkQdsd4dMqY",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "triceps", stress: "HIGH" },
      { muscle: "pects", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_FrontRaise",
    name: "Front Raise",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_FrontRaise.mp4",
    fullVideoUrl: "https://youtu.be/syMfvRErcPk",
    movementType: "MISC",
    muscleType: "SHOULDERS",
    muscleGroups: [{ muscle: "shoulders", stress: "HIGH" }],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_FrontSquat",
    name: "Front Squat",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_FrontSquat.mp4",
    fullVideoUrl: "https://youtu.be/b9EH4mxfghE",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_GluteBridge",
    name: "Glute Bridge",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_GluteBridge.mp4",
    fullVideoUrl: "https://youtu.be/RKtlMDr0ggQ",
    movementType: "HIP_HINGE",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "glutes", stress: "HIGH" },
      { muscle: "hamstrings", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_GluteHamRaise",
    name: "Glute Ham Raise",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_GluteHamRaise.mp4",
    fullVideoUrl: "https://youtu.be/n1fj47zuWuo",
    movementType: "HIP_HINGE",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "hamstrings", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_GoodMorning",
    name: "Good Morning",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_GoodMorning.mp4",
    fullVideoUrl: "https://youtu.be/VvVpBdrlvzM",
    movementType: "HIP_HINGE",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "glutes", stress: "HIGH" },
      { muscle: "hamstrings", stress: "HIGH" },
      { muscle: "quads", stress: "LOW" },
      { muscle: "lower_back", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_HackSquat",
    name: "Hack Squat",
    shortVideoUrl: "",
    fullVideoUrl: "",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "MACHINE",
    warmupType: "MACHINE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_HammerCurl",
    name: "Hammer Curl",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_HammerCurl.mp4",
    fullVideoUrl: "https://youtu.be/Stl1semQH3M",
    movementType: "MISC",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "biceps", stress: "HIGH" },
      { muscle: "forearms", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_HangingKneeRaises",
    name: "Hanging Knee Raises",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_HangingKneeRaises.mp4",
    fullVideoUrl: "https://youtu.be/11i5QrOrn6c",
    movementType: "MISC",
    muscleType: "ABS",
    muscleGroups: [
      { muscle: "hip_flexors", stress: "HIGH" },
      { muscle: "abs", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_HangingLegRaise",
    name: "Hanging Leg Raises",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_HangingLegRaise.mp4",
    fullVideoUrl: "https://youtu.be/Ie5zokfvhcE",
    movementType: "MISC",
    muscleType: "ABS",
    muscleGroups: [
      { muscle: "hip_flexors", stress: "HIGH" },
      { muscle: "abs", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_HighBarSquat",
    name: "High Bar Squat",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_HighBarSquat.mp4",
    fullVideoUrl: "https://youtu.be/EFI5TbAjaTM",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_HipBeltSquat",
    name: "Hip Belt Squat",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_HipBeltSquat.mp4",
    fullVideoUrl: "https://youtu.be/p2HBb5UmVSg",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "MACHINE",
    warmupType: "MACHINE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_HitThrust",
    name: "Hip Thrust",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_HitThrust.mp4",
    fullVideoUrl: "https://youtu.be/fQB3GfhFQ54",
    movementType: "HIP_HINGE",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "glutes", stress: "HIGH" },
      { muscle: "hamstrings", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_Hyperextension",
    name: "Hyperextension",
    shortVideoUrl: "",
    fullVideoUrl: "",
    movementType: "HIP_HINGE",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lower_back", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "upper_traps", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "NONE",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_InclineBenchPress",
    name: "Incline Bench Press",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_InclineBenchPress.mp4",
    fullVideoUrl: "https://youtu.be/WrBVKqc1jO0",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "shoulders", stress: "LOW" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_InclineBoardPress",
    name: "Incline Board Press",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_InclineBoardPress.mp4",
    fullVideoUrl: "https://youtu.be/YNwzP_uADgY",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "shoulders", stress: "LOW" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_InclineDumbbellBench",
    name: "Incline Dumbbell Bench Press",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_InclineDumbbellBench.mp4",
    fullVideoUrl: "https://youtu.be/AR7B8k4rl9c",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "shoulders", stress: "LOW" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_InvertedRow",
    name: "Inverted Row",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_InvertedRow.mp4",
    fullVideoUrl: "https://youtu.be/BoT5Z7l6Jh4",
    movementType: "HORIZONTAL_PULL",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lats", stress: "HIGH" },
      { muscle: "traps", stress: "LOW" },
      { muscle: "biceps", stress: "LOW" },
      { muscle: "rear_delts", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_LatPulldown",
    name: "Lat Pulldown",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_LatPulldown.mp4",
    fullVideoUrl: "https://youtu.be/xJrkbB8y_vg",
    movementType: "VERTICAL_PULL",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lats", stress: "HIGH" },
      { muscle: "biceps", stress: "LOW" },
      { muscle: "forearms", stress: "LOW" },
    ],
    weightType: "MACHINE",
    warmupType: "MACHINE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_LegCurl",
    name: "Leg Curl",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_LegCurl.mp4",
    fullVideoUrl: "https://youtu.be/8ws_sKtQm2M",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "hamstrings", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
    ],
    weightType: "MACHINE",
    warmupType: "MACHINE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_LegExtension",
    name: "Leg Extension",
    shortVideoUrl: "",
    fullVideoUrl: "",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [{ muscle: "quads", stress: "HIGH" }],
    weightType: "MACHINE",
    warmupType: "MACHINE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_LegPress",
    name: "Leg Press",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_LegPress.mp4",
    fullVideoUrl: "https://youtu.be/awMwuM-0bVw",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "MACHINE",
    warmupType: "MACHINE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_LeverRow",
    name: "Lever Row",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_LeverRow.mp4",
    fullVideoUrl: "https://youtu.be/jeY3d_C6TFE",
    movementType: "HORIZONTAL_PULL",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lats", stress: "HIGH" },
      { muscle: "traps", stress: "LOW" },
      { muscle: "biceps", stress: "LOW" },
      { muscle: "rear_delts", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_Lunges",
    name: "Lunges",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_Lunges.mp4",
    fullVideoUrl: "https://youtu.be/dY9JzF07Dxk",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_LungesFrontLoaded",
    name: "Lunges (Front Loaded)",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_LungesFrontLoaded.mp4",
    fullVideoUrl: "https://youtu.be/1sIw9ln5vyU",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_MachineRow",
    name: "Seated Lever Row",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_MachineRow.mp4",
    fullVideoUrl: "https://youtu.be/_a2OU7xLoms",
    movementType: "HORIZONTAL_PULL",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lats", stress: "HIGH" },
      { muscle: "traps", stress: "LOW" },
      { muscle: "biceps", stress: "LOW" },
      { muscle: "rear_delts", stress: "LOW" },
    ],
    weightType: "MACHINE",
    warmupType: "MACHINE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_MilitaryPress",
    name: "Military Press",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_MilitaryPress.mp4",
    fullVideoUrl: "https://youtu.be/07hSwX7NMt4",
    movementType: "VERTICAL_PUSH",
    muscleType: "SHOULDERS",
    muscleGroups: [
      { muscle: "shoulders", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_OverheadPress",
    name: "Overhead Press",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_OverheadPress.mp4",
    fullVideoUrl: "https://youtu.be/4TSmHC46Kaw",
    movementType: "VERTICAL_PUSH",
    muscleType: "SHOULDERS",
    muscleGroups: [
      { muscle: "shoulders", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_OverheadPressLandmine",
    name: "Overhead Press Landmine",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_OverheadPressLandmine.mp4",
    fullVideoUrl: "https://youtu.be/B0GNi62Fbz0",
    movementType: "VERTICAL_PUSH",
    muscleType: "SHOULDERS",
    muscleGroups: [
      { muscle: "shoulders", stress: "HIGH" },
      { muscle: "pects", stress: "LOW" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_OverheadPressSeated",
    name: "Overhead Press Seated",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_OverheadPressSeated.mp4",
    fullVideoUrl: "https://youtu.be/5aM3m1F315U",
    movementType: "VERTICAL_PUSH",
    muscleType: "SHOULDERS",
    muscleGroups: [
      { muscle: "shoulders", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_PallofPress",
    name: "Pallof Press",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_PallofPress.mp4",
    fullVideoUrl: "https://youtu.be/sCtl45_VPOw",
    movementType: "MISC",
    muscleType: "ABS",
    muscleGroups: [
      { muscle: "obliques", stress: "HIGH" },
      { muscle: "abs", stress: "LOW" },
    ],
    weightType: "MACHINE",
    warmupType: "MACHINE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_PausedBenchPress",
    name: "Paused Bench Press",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_PausedBenchPress.mp4",
    fullVideoUrl: "https://youtu.be/YYzFm4Orc_Q",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_PauseDeadliftHigh",
    name: "Pause Deadlift (High)",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_PauseDeadliftHigh.mp4",
    fullVideoUrl: "https://youtu.be/l0xaURXg64c",
    movementType: "HIP_HINGE",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lower_back", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "upper_traps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_PauseDeadliftLow",
    name: "Pause Deadlift (Low)",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_PauseDeadliftLow.mp4",
    fullVideoUrl: "https://youtu.be/UZvEOZjyfNs",
    movementType: "HIP_HINGE",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lower_back", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "upper_traps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_PauseSquat",
    name: "Pause Squat",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_PauseSquat.mp4",
    fullVideoUrl: "https://youtu.be/OUiRSkfzEEE",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_PinPressChest",
    name: "Pin Press (chest)",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_PinPressChest.mp4",
    fullVideoUrl: "https://youtu.be/MZUkeZzHCuw",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_PinPressChestTempo300",
    name: "Pin Press (chest) 300 Tempo",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_PinPressChestTempo300.mp4",
    fullVideoUrl: "https://youtu.be/GG5RXhB5nRk",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_PinPressIncline",
    name: "Pin Press Incline",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_PinPressIncline.mp4",
    fullVideoUrl: "https://youtu.be/ZH3go-vMu5I",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "shoulders", stress: "LOW" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_PinPressMid",
    name: "Pin Press (mid-range)",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_PinPressMid.mp4",
    fullVideoUrl: "https://youtu.be/2Jcy-UeY9k4",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "triceps", stress: "HIGH" },
      { muscle: "pects", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_PinSquat",
    name: "Pin Squat",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_PinSquat.mp4",
    fullVideoUrl: "https://youtu.be/eiXPFA9ID5Y",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_PinSquatHighBarTempo300",
    name: "Pin Squat High Bar 300 Tempo",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_PinSquatHighBarTempo300.mp4",
    fullVideoUrl: "https://youtu.be/tz2Gk7jfluc",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_Planks",
    name: "Planks",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_Planks.mp4",
    fullVideoUrl: "https://youtu.be/mZUmMESzDPU",
    movementType: "MISC",
    muscleType: "ABS",
    muscleGroups: [
      { muscle: "abs", stress: "HIGH" },
      { muscle: "obliques", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_PullUps",
    name: "Pullups",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_PullUps.mp4",
    fullVideoUrl: "https://youtu.be/keFMU9oeSm0",
    movementType: "VERTICAL_PULL",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lats", stress: "HIGH" },
      { muscle: "biceps", stress: "LOW" },
      { muscle: "forearms", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_PushPress",
    name: "Push Press",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_PushPress.mp4",
    fullVideoUrl: "https://youtu.be/d0qLYdK32vE",
    movementType: "VERTICAL_PUSH",
    muscleType: "SHOULDERS",
    muscleGroups: [
      { muscle: "shoulders", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_PushUps",
    name: "Pushups",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_PushUps.mp4",
    fullVideoUrl: "https://youtu.be/zi-A6b48zBw",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_RackPull",
    name: "Rack Pull",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_RackPull.mp4",
    fullVideoUrl: "https://youtu.be/bOut_fdXV3o",
    movementType: "HIP_HINGE",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lower_back", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "upper_traps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_RearDeltRaise",
    name: "Rear Delt Raise",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_RearDeltRaise.mp4",
    fullVideoUrl: "https://youtu.be/zXHtDx57QmY",
    movementType: "MISC",
    muscleType: "SHOULDERS",
    muscleGroups: [
      { muscle: "rear_delts", stress: "HIGH" },
      { muscle: "traps", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_ReverseCrunch",
    name: "Reverse Crunch",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_ReverseCrunch.mp4",
    fullVideoUrl: "https://youtu.be/6XK3DLIfUDs",
    movementType: "MISC",
    muscleType: "ABS",
    muscleGroups: [
      { muscle: "abs", stress: "HIGH" },
      { muscle: "hip_flexors", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_ReverseLunges",
    name: "Reverse Lunges",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_ReverseLunges.mp4",
    fullVideoUrl: "https://youtu.be/NYjZ8HGgxZE",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_ReverseLungeSafetySquatBar",
    name: "Reverse Lunge Safety Squat Bar",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_ReverseLungeSafetySquatBar.mp4",
    fullVideoUrl: "https://youtu.be/8ghArIkIAh8",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_RomanChairSitup",
    name: "Roman Chair Situp",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_RomanChairSitup.mp4",
    fullVideoUrl: "https://youtu.be/vSoRqwdV-W8",
    movementType: "MISC",
    muscleType: "ABS",
    muscleGroups: [
      { muscle: "abs", stress: "HIGH" },
      { muscle: "obliques", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_RomanianDeadlift",
    name: "Romanian Deadlift",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_RomanianDeadlift.mp4",
    fullVideoUrl: "https://youtu.be/9HllpJGJQ2E",
    movementType: "HIP_HINGE",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "hamstrings", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "lower_back", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_RussianTwist",
    name: "Russian Twist",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_RussianTwist.mp4",
    fullVideoUrl: "https://youtu.be/d57oMCz4N5Y",
    movementType: "MISC",
    muscleType: "ABS",
    muscleGroups: [
      { muscle: "obliques", stress: "HIGH" },
      { muscle: "abs", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_SafetyBarBulgarianSplitSquat",
    name: "Safety Bar Bulgarian Split Squat",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_SafetyBarBulgarianSplitSquat.mp4",
    fullVideoUrl: "https://youtu.be/Sjbhq9JItyA",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_SafetyBarSquat",
    name: "Safety Bar Squat",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_SafetyBarSquat.mp4",
    fullVideoUrl: "https://youtu.be/FcL0IVO9Msc",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_SafetyBarSquatTempo310",
    name: "Safety Bar Squat 310 Tempo",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_SafetyBarSquatTempo310.mp4",
    fullVideoUrl: "https://youtu.be/4oMH6zgamJk",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_SafetyBarSquatTempo530",
    name: "Safety Bar Squat 530 Tempo",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_SafetyBarSquatTempo530.mp4",
    fullVideoUrl: "https://youtu.be/5IK_Mkx77mM",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_SeatedCalfRaises",
    name: "Seated Calf Raises",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_SeatedCalfRaises.mp4",
    fullVideoUrl: "https://youtu.be/eIhMtMzHVEY",
    movementType: "MISC",
    muscleType: "LEGS",
    muscleGroups: [{ muscle: "calfs", stress: "HIGH" }],
    weightType: "BARBELL",
    warmupType: "BAR_ISO",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_SeatedRow",
    name: "Seated Row",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_SeatedRow.mp4",
    fullVideoUrl: "https://youtu.be/l-DslBiDyns",
    movementType: "HORIZONTAL_PULL",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lats", stress: "HIGH" },
      { muscle: "traps", stress: "LOW" },
      { muscle: "biceps", stress: "LOW" },
      { muscle: "rear_delts", stress: "LOW" },
    ],
    weightType: "MACHINE",
    warmupType: "MACHINE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_SideLunge",
    name: "Side Lunge",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_SideLunge.mp4",
    fullVideoUrl: "https://youtu.be/PytI6D_eqpo",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "abductors", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "quads", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_SidePlanks",
    name: "Side Planks",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_SidePlanks.mp4",
    fullVideoUrl: "https://youtu.be/INqUEmwGOes",
    movementType: "MISC",
    muscleType: "ABS",
    muscleGroups: [
      { muscle: "obliques", stress: "HIGH" },
      { muscle: "abs", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_SideRaise",
    name: "Side Raise",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_SideRaise.mp4",
    fullVideoUrl: "https://youtu.be/n1Z3t__ebV8",
    movementType: "MISC",
    muscleType: "SHOULDERS",
    muscleGroups: [{ muscle: "shoulders", stress: "HIGH" }],
    weightType: "DUMBBELL",
    warmupType: "DUMBBELL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_Situp",
    name: "Situp",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_Situp.mp4",
    fullVideoUrl: "https://youtu.be/e4drOJn0W2Q",
    movementType: "MISC",
    muscleType: "ABS",
    muscleGroups: [
      { muscle: "abs", stress: "HIGH" },
      { muscle: "obliques", stress: "LOW" },
    ],
    weightType: "BODYWEIGHT",
    warmupType: "BODYWEIGHT",
    warmupEnabledByDefault: false,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_Skullcrushers",
    name: "Skullcrushers",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_Skullcrushers.mp4",
    fullVideoUrl: "https://youtu.be/LSGjDvVhOoE",
    movementType: "MISC",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "triceps", stress: "HIGH" },
      { muscle: "forearms", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_ISO",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_SplitSquat",
    name: "Split Squat",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_SplitSquat.mp4",
    fullVideoUrl: "https://youtu.be/k9cJPbvkPFY",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_Squat",
    name: "Squat",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_Squat.mp4",
    fullVideoUrl: "https://youtu.be/t-VbGzEQQHY",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_StandingCalfRaises",
    name: "Standing Calf Raises",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_StandingCalfRaises.mp4",
    fullVideoUrl: "https://youtu.be/LSdacuD23Eg",
    movementType: "MISC",
    muscleType: "LEGS",
    muscleGroups: [{ muscle: "calfs", stress: "HIGH" }],
    weightType: "BARBELL",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_Stepup",
    name: "Stepup",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_Stepup.mp4",
    fullVideoUrl: "https://youtu.be/RgFB2U6H8Qo",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_StiffLegDeadlift",
    name: "Stiff Leg Deadlift",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_StiffLegDeadlift.mp4",
    fullVideoUrl: "https://youtu.be/PV6BwWg1HQg",
    movementType: "HIP_HINGE",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "hamstrings", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "lower_back", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_SuitcaseDeadlift",
    name: "Suitcase Deadlift",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_SuitcaseDeadlift.mp4",
    fullVideoUrl: "https://youtu.be/xYdxr33Vu5g",
    movementType: "HIP_HINGE",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lower_back", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "upper_traps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_SumoDeadlift",
    name: "Sumo Deadlift",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_SumoDeadlift.mp4",
    fullVideoUrl: "https://youtu.be/A-WH2epoeBs",
    movementType: "HIP_HINGE",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lower_back", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "upper_traps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_SumoDeadliftTempo530",
    name: "Sumo Deadlift 530 Tempo",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_SumoDeadliftTempo530.mp4",
    fullVideoUrl: "https://youtu.be/clFu5baRqz0",
    movementType: "HIP_HINGE",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lower_back", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "upper_traps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_SwissBarBenchFeetUp",
    name: "Swiss Bar Bench Feet Up",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_SwissBarBenchFeetUp.mp4",
    fullVideoUrl: "https://youtu.be/s1qcSfS1-GQ",
    movementType: "HORIZONTAL_PULL",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "NONE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_TempoBarbellRow530",
    name: "Tempo Barbell Row 530",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_TempoBarbellRow530.mp4",
    fullVideoUrl: "https://youtu.be/JSDgDF-MK0U",
    movementType: "HORIZONTAL_PULL",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "lats", stress: "HIGH" },
      { muscle: "traps", stress: "LOW" },
      { muscle: "biceps", stress: "LOW" },
      { muscle: "rear_delts", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_TempoBench530",
    name: "Tempo Bench 530",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_TempoBench530.mp4",
    fullVideoUrl: "https://youtu.be/LrFL7P79-Ek",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_TempoBench600",
    name: "Tempo Bench 600",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_TempoBench600.mp4",
    fullVideoUrl: "https://youtu.be/hnjJi1ZhT64",
    movementType: "HORIZONTAL_PUSH",
    muscleType: "CHEST",
    muscleGroups: [
      { muscle: "pects", stress: "HIGH" },
      { muscle: "triceps", stress: "LOW" },
      { muscle: "shoulders", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_TempoSquat530",
    name: "Tempo Squat 530",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_TempoSquat530.mp4",
    fullVideoUrl: "https://youtu.be/_8wPvQfzlHE",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_TempoSquat600",
    name: "Tempo Squat 600",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_TempoSquat600.mp4",
    fullVideoUrl: "https://youtu.be/upTgL7mAUfA",
    movementType: "SQUAT",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "quads", stress: "HIGH" },
      { muscle: "glutes", stress: "LOW" },
      { muscle: "hamstrings", stress: "LOW" },
      { muscle: "abductors", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_MAIN",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_TrapBarDeadlift",
    name: "Trap Bar Deadlift",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_TrapBarDeadlift.mp4",
    fullVideoUrl: "https://youtu.be/CCb7L6Mzu5o",
    movementType: "HIP_HINGE",
    muscleType: "LEGS",
    muscleGroups: [
      { muscle: "glutes", stress: "HIGH" },
      { muscle: "hamstrings", stress: "HIGH" },
      { muscle: "quads", stress: "LOW" },
      { muscle: "lower_back", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_TricepsExtension",
    name: "Triceps Extension",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_TricepsExtension.mp4",
    fullVideoUrl: "https://youtu.be/H0pfIXI2vig",
    movementType: "MISC",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "triceps", stress: "HIGH" },
      { muscle: "forearms", stress: "LOW" },
    ],
    weightType: "DUMBBELL",
    warmupType: "BAR_ISO",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_TricepsPushdown",
    name: "Triceps Pushdown",
    shortVideoUrl:
      "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_TricepsPushdown.mp4",
    fullVideoUrl: "https://youtu.be/h2_PsxpAvkc",
    movementType: "MISC",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "triceps", stress: "HIGH" },
      { muscle: "forearms", stress: "LOW" },
    ],
    weightType: "MACHINE",
    warmupType: "MACHINE",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
  {
    id: "SL_UprightRow",
    name: "Upright Row",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_UprightRow.mp4",
    fullVideoUrl: "https://youtu.be/QArUbFjkI-A",
    movementType: "MISC",
    muscleType: "BACK",
    muscleGroups: [
      { muscle: "upper_traps", stress: "HIGH" },
      { muscle: "shoulders", stress: "HIGH" },
      { muscle: "biceps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_PULL",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: true,
    defaultBarbellWeightKg: 20,
    defaultBarbellWeightLb: 40,
  },
  {
    id: "SL_WristCurl",
    name: "Wrist Curl",
    shortVideoUrl: "https://slvideos.nyc3.cdn.digitaloceanspaces.com/android/SL_WristCurl.mp4",
    fullVideoUrl: "https://youtu.be/o8y9IGTKivs",
    movementType: "MISC",
    muscleType: "ARMS",
    muscleGroups: [
      { muscle: "forearms", stress: "HIGH" },
      { muscle: "biceps", stress: "LOW" },
    ],
    weightType: "BARBELL",
    warmupType: "BAR_ISO",
    warmupEnabledByDefault: true,
    usesBarbellWeightInWarmup: false,
    defaultBarbellWeightKg: 0,
    defaultBarbellWeightLb: 0,
  },
];

export type ExerciseId = (typeof exercises)[number]["id"];
